- import_playbook: kn6plv.aredn.base

- hosts: all
  gather_facts: yes
  serial: 1
  tasks:
  - name: Update firmware
    include_tasks: tasks/firmware_update.yml
  handlers:
  - name: Smoke test
    include_tasks: tasks/smoke_test.yml
    listen: firmware updated
